app_name: mortred
status:
    STATUS_ACTIVE: 99
    STATUS_INACTIVE: 98
    STATUS_DELETED: 97
    STATUS_PENDING: 96
    STATUS_BLOCKED: 95
    STATUS_BANNED: 94
    STATUS_ARCHIVED: 93
    STATUS_REJECTED: 92
    STATUS_ACCEPTED: 91
    STATUS_NEED_CONFIRMATION: 90

queue_topics:
    SEARCH_INDEXING: elasticsearch_index
